name: psplash
version: '0.1'
summary: display a fullscreen splash screen on Ubuntu Core devices
description: |
  This is a build of the poky psplash tool, it is run as a service on system
  startup and will display a fulllscreen Ubuntu Core logo on embedded devices
architectures:
  - armhf
grade: stable
confinement: devmode

apps:
  psplash:
    command: psplash
    daemon: simple
  psplash-write:
    command: psplash-write

parts:
  psplash:
    source: git://git.yoctoproject.org/psplash
    plugin: make
    prepare: |
      aclocal
      autoreconf --install
      ./configure --host=arm-linux CC=/usr/bin/arm-linux-gnueabihf-gcc
      cp ../../../core_black-orange_st_hex.png psplash-poky.png
      ./make-image-header.sh psplash-poky.png POKY
      git apply ../../../psplash-hide-progress.patch
    build: |
      make
    install: |
      cp psplash $SNAPCRAFT_PART_INSTALL/
      cp psplash-writeCRAFT_PART_INSTALL/
    build-packages:
      - libgdk-pixbuf2.0-dev
      - sed
      - automake
      - autoconf
      - gcc-arm-linux-gnueabihf
