name: psplash
version: '0.1'
summary: display a fullscreen splash screen on Ubuntu Core devices
description: |
  This is a build of the poky psplash tool, it is run as a service on system
  startup and will display a fullscreen Ubuntu Core logo on embedded devices
architectures:
  - armhf
grade: stable
confinement: devmode

apps:
  psplash:
    command: psplash
    daemon: simple
    plugs: [network, network-bind, framebuffer]
  psplash-write:
    command: psplash-write
    plugs: [network, network-bind]
  showlogin:
    command: showlogin.sh
    daemon: simple
    plugs: [network, network-bind]

parts:
  psplash:
    source: git://git.yoctoproject.org/psplash
    plugin: make
    prepare: |
      export TREE="../../.."
      . ${TREE}/config
      if ! $(echo "$FONT"|grep -q ^/); then \
         FONT="${TREE}/${FONT}"; \
      fi
      if ! $(echo "$SPLASH"|grep -q ^/); then \
         SPLASH="${TREE}/${SPLASH}"; \
      fi
      git apply ${TREE}/psplash.patch
      ${TREE}/font-gen.sh "$FONT"
      ./make-image-header.sh "$SPLASH" CORE psplash-core
      aclocal
      autoreconf --install
      if [ "$(arch)" != "armv7l" ]; then \
        if [ ! -e "/usr/bin/arm-linux-gnueabihf-gcc" ]; then \
          echo "ERROR: install gcc-arm-linux-gnueabihf to cross build this snap!"; \
          exit 1; \
        fi
        ./configure --host=arm-linux CC=/usr/bin/arm-linux-gnueabihf-gcc; \
      else \
        ./configure; \
      fi
    build: |
      make
    install: |
      cp psplash $SNAPCRAFT_PART_INSTALL/
      cp psplash-write $SNAPCRAFT_PART_INSTALL/
      cp ../../../showlogin.sh $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - libgdk-pixbuf2.0-dev
      - automake
      - autoconf
      - gcc
      - otf2bdf
      - libbogl-dev
      - ttf-ubuntu-font-family
