name: psplash
version: '0.1'
summary: display a fullscreen splash screen on Ubuntu Core devices
description: |
  This is a build of the poky psplash tool, it is run as a service on system
  startup and will display a fullscreen Ubuntu Core logo on embedded devices
architectures:
  - armhf
grade: stable
confinement: devmode

apps:
  psplash:
    command: psplash
    daemon: simple
  psplash-write:
    command: psplash-write

parts:
  psplash:
    source: git://git.yoctoproject.org/psplash
    plugin: make
    prepare: |
      . ../../../config
      aclocal
      autoreconf --install
      ./configure --host=arm-linux CC=/usr/bin/arm-linux-gnueabihf-gcc
      git apply ../../../psplash.patch
      ../../../font-gen.sh "$FONT"
      ./make-image-header.sh "../../../${SPLASH}" CORE psplash-core
    build: |
      make
    install: |
      cp psplash $SNAPCRAFT_PART_INSTALL/
      cp psplash-write $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - libgdk-pixbuf2.0-dev
      - automake
      - autoconf
      - gcc-arm-linux-gnueabihf
      - otf2bdf
      - libbogl-dev
      - ttf-ubuntu-font-family
